### PR TITLE
ENH: Initial commit of dpc demo code

### PR DESCRIPTION
**Pull request by thegreatwall**

### CODE REVIEW

**Comment by ericdill** [comment]
@tacaswell Do you know the status of this example?  What portion of this code already exists in skxray?

**Comment by tacaswell** [comment]
Almost all of this got turned into a function.

@thegreatwall Can you update this example to use `dpc_runner`?

**Comment by thegreatwall** [comment]
Is it in a hurry? I have a paper abstract deadline tomorrow and full paper deadline next week.


> On Jan 8, 2015, at 2:17 PM, Thomas A Caswell <notifications@github.com> wrote:
> 
> Almost all of this got turned into a function.
> 
> @thegreatwall <https://github.com/thegreatwall> Can you update this example to use dpc_runner?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Nikea/scikit-xray-examples/pull/4#issuecomment-69232450>.
> 

--
Best Regards,

  Cheng Chang 
  Computer Engineering, Stony Brook University
  Computer Science Group, Computational Science Center, Brookhaven National Laboratory
  Tel：(001) 631-885-4922

**Comment by tacaswell** [comment]
@danielballan This should be re-written to use the dpc functions in skxray.

**Comment by tacaswell** [comment]
ahh, I now see what happened.  

To future readers: this got consumed by #17

**Pull request merged**
