### PR TITLE
Ipython notebook for multi tau auto correlation

### PR DESCRIPTION
**Pull request by sameera2004**
...A Gel data

### CODE REVIEW

**Comment by danielballan** [comment]
Could you revise this against the new ROI API?

**Comment by sameera2004** [comment]
@danielballan changed this python notebooks to use new ROI Api

**Comment by danielballan** [comment]
For others, here an [nbviewer link](http://nbviewer.ipython.org/github/sameera2004/scikit-xray-examples/blob/mt_corr_example/notebooks/time_correlation/.ipynb_checkpoints/Multi_tau_one_time_correlation_example-checkpoint.ipynb).

**Comment by sameera2004** [comment]
@danielballan If there is nothing more to add to this ipython notebook can you please merge this? I want to add more examples as we discussed and two time correlation ipython notebook with the same data set. However, I don't want to add more files to this PR,

**Comment by danielballan** [comment]
And again [the link](http://nbviewer.ipython.org/github/sameera2004/scikit-xray-examples/blob/fe820557fcc7885e2eed622125fa1ae8187a35a6/notebooks/time_correlation/Multi_tau_one_time_correlation_example.ipynb)

**Pull request merged**
