### PR TITLE
Dpc

### PR DESCRIPTION
**Pull request by ericdill**
Supersedes #4

### CODE REVIEW

**Comment by danielballan** [comment]
Cool. Let's sit on this in the hope of getting git large file storage enabled before we really need it merged.

**Comment by ericdill** [comment]
What is the eta on getting LFS enabled?

**Comment by ericdill** [comment]
Actually, I only included the data in this PR because I was being paranoid about it no longer being available via someone's dropbox account (https://www.dropbox.com/s/963c4ymfmbjg5dm/SOFC.zip). I'll keep a copy of it on my laptop until LFS is enabled and remove it from this PR

**Comment by danielballan** [comment]
Solid. No ETA, but I did get an email saying, essentially, "soon!"

**Comment by ericdill** [comment]
Hadn't quite finished yet, but you had no way of knowing that... See #19

**Comment by ericdill** [comment]
Thanks for the merge!

**Pull request merged**
