### PR TITLE
ENH: adding an example for one time correlation - ipython notebook is ad...

### PR DESCRIPTION
**Pull request by sameera2004**
ipython notebook is added with image data to check skxray/correlation.py

### CODE REVIEW

**Comment by sameera2004** [comment]
http://localhost:8891/nbconvert/html/one_time_correlation_example_1.ipynb?download=false

Attach please find another python notebook using (9950 images of C4B_T_250K)

**Comment by ericdill** [comment]
Can't see that notebook since it's on your local machine (thus the localhost in the url)

You can, however, copy the [ipython notebook code] (https://raw.githubusercontent.com/sameera2004/scikit-xray-examples/one_time_corr_example/notebooks/one_time_correlation/.ipynb_checkpoints/one_time_correlation_example_1-checkpoint.ipynb) into [a gist] (https://gist.github.com/ericdill/bd883734d9b7fe009014) and then copy the gist link into the text box at http://nbviewer.ipython.org/ to create a web hosted notebook [like this] (http://nbviewer.ipython.org/gist/ericdill/bd883734d9b7fe009014).

The notebook looks great, thanks for the example!

This is a cousin PR to Nikea/scikit-xray#254?

@danielballan any suggestions about making comments on ipython notebooks?

**Comment by sameera2004** [comment]
Sure, Thanks I will create the notebook in this way.

Yes this is example for https://github.com/Nikea/scikit-xray/pull/254

**Comment by sameera2004** [comment]
http://nbviewer.ipython.org/urls/gist.githubusercontent.com/ericdill/bd883734d9b7fe009014/raw/e220247c0a0a9b9bb31c89d4a219d7aceaf9add4/gistfile1.txt

@ericdill Can you see the notebook now?

**Comment by ericdill** [comment]
Sure can! Thanks :smile:

**Comment by sameera2004** [comment]
Closing due to changes in the module correlation.py. Will add a new python notebook

**Pull request closed without merging**
